// The timer/<deviceId>/<event> MQTT contract; field names are fixed by the ESP32 firmware.

export enum DisplayState {
  STARTUP = 'STARTUP',
  DISCONNECTED = 'DISCONNECTED',
  SCANNING = 'SCANNING',
  CONNECTING = 'CONNECTING',
  CONNECTED = 'CONNECTED',
  COUNTDOWN = 'COUNTDOWN',
  WAITING_FOR_SHOTS = 'WAITING_FOR_SHOTS',
  SHOWING_SHOT = 'SHOWING_SHOT',
  SESSION_ENDED = 'SESSION_ENDED'
}

export enum ConnectionState {
  DISCONNECTED = 'DISCONNECTED',
  SCANNING = 'SCANNING',
  CONNECTING = 'CONNECTING',
  CONNECTED = 'CONNECTED',
  ERROR = 'ERROR'
}

export type DevicePresence = 'online' | 'offline';

export interface ShotData {
  sessionId: number;
  shotNumber: number;
  absoluteTimeMs: number;
  splitTimeMs: number;
  deviceModel: string;
  isFirstShot: boolean;
  timestamp: number;
}

export interface SessionData {
  sessionId: number;
  isActive: boolean;
  totalShots: number;
  startTimestamp: number;
  startDelaySeconds: number;
  countdownStartTime: number;
}

export interface MqttSettings {
  broker: string;
  username: string;
  password: string;
  clientId: string;
  brightness?: number;
}

export interface MqttServerConfig {
  wsUrl: string | null;
  username: string;
  password: string;
}

export interface ConnectionStateMessage {
  state: ConnectionState;
  deviceName?: string;
  deviceModel?: string;
  timestamp: number;
}

export interface SessionStartedMessage {
  sessionId: number;
  timestamp: number;
  startDelaySeconds?: number;
}

export interface SessionStoppedMessage {
  sessionId: number;
  totalShots?: number;
  lastShotTimeMs?: number;
  timestamp: number;
}

/** Published by the timekeeper after a session stops; the firmware matches it on `sessionId`. */
export interface SessionUpNextMessage {
  sessionId: number;
  next: string;
  onDeck?: string;
}

export interface ShotDetectedMessage {
  sessionId: number;
  shotNumber: number;
  absoluteTimeMs: number;
  splitTimeMs: number;
  deviceModel: string;
  isFirstShot: boolean;
  timestamp: number;
}

export interface CountdownCompleteMessage {
  sessionId: number;
  timestamp: number;
}

export interface DeviceInfoMessage {
  deviceName?: string;
  deviceModel?: string;
  firmwareVersion?: string;
  deviceId?: string;
  timestamp: number;
}

/** `deviceId` comes from the topic, not the payload. */
export type MqttMessageHandler<T = any> = (message: T, deviceId: string) => void;

export interface KnownDevice {
  /** 6-char alphanumeric, generated by the firmware's DeviceId. */
  deviceId: string;
  deviceName?: string;
  deviceModel?: string;
  firmwareVersion?: string;
  presence: DevicePresence;
  lastSeenMs: number;
}

export interface DevicePresenceMessage {
  presence: DevicePresence;
}

export interface DeviceTopic {
  deviceId: string;
  event: string;
}

/** Subscription patterns: '+' matches any device, so one subscription covers them all. */
export interface MqttTopics {
  PRESENCE: string;
  CONNECTION_STATE: string;
  SESSION_STARTED: string;
  SESSION_STOPPED: string;
  SESSION_SUSPENDED: string;
  SESSION_RESUMED: string;
  SHOT_DETECTED: string;
  COUNTDOWN_COMPLETE: string;
  DEVICE_INFO: string;
}
