/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    shooters: Shooter;
    devices: Device;
    matches: Match;
    squads: Squad;
    'squad-memberships': SquadMembership;
    'round-results': RoundResult;
    'match-sessions': MatchSession;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    matches: {
      squads: 'squads';
    };
    squads: {
      memberships: 'squad-memberships';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    shooters: ShootersSelect<false> | ShootersSelect<true>;
    devices: DevicesSelect<false> | DevicesSelect<true>;
    matches: MatchesSelect<false> | MatchesSelect<true>;
    squads: SquadsSelect<false> | SquadsSelect<true>;
    'squad-memberships': SquadMembershipsSelect<false> | SquadMembershipsSelect<true>;
    'round-results': RoundResultsSelect<false> | RoundResultsSelect<true>;
    'match-sessions': MatchSessionsSelect<false> | MatchSessionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'timekeeper';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shooters".
 */
export interface Shooter {
  id: number;
  firstName: string;
  lastName: string;
  asnNumber?: string | null;
  /**
   * Barcode scan lookup key. Leave blank if the shooter has no card.
   */
  knsaNumber?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "devices".
 */
export interface Device {
  id: number;
  /**
   * The firmware's 6-character device ID, as published on timer/<deviceId>/... MQTT topics.
   */
  deviceId: string;
  /**
   * Friendly name shown when the timekeeper picks a device, e.g. "Lane 3".
   */
  label: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "matches".
 */
export interface Match {
  id: number;
  /**
   * e.g. "Saturday match, 30 August".
   */
  label?: string | null;
  /**
   * The one timer used for every squad rotating through this match.
   */
  device: number | Device;
  squads?: {
    docs?: (number | Squad)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "squads".
 */
export interface Squad {
  id: number;
  /**
   * Optional friendly name, e.g. "08:00 squad".
   */
  label?: string | null;
  /**
   * The match this squad rotates through — its timer device comes from here, not from the squad.
   */
  match: number | Match;
  /**
   * e.g. "08:00"
   */
  startTime: string;
  /**
   * e.g. "09:00"
   */
  endTime: string;
  status: 'scheduled' | 'active' | 'reshoot-phase' | 'completed';
  memberships?: {
    docs?: (number | SquadMembership)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "squad-memberships".
 */
export interface SquadMembership {
  id: number;
  squad: number | Squad;
  shooter: number | Shooter;
  discipline: 'OKP' | 'OKKP' | 'SKP' | 'SKKP' | 'PCC 9mm' | 'PCC .22' | 'OKR' | 'OKKR' | 'SKR' | 'SKKR';
  /**
   * Position number from the printed schedule — the starting order only.
   */
  startingPosition: number;
  /**
   * Current position in the live shooting queue. Mutable mid-match; renumbered on every queue mutation.
   */
  queuePosition: number;
  status: 'scheduled' | 'present' | 'absent' | 'withdrawn';
  /**
   * The one allowed reshoot, in milliseconds. Overwritable before sign-off; blank until taken.
   */
  reshootTimeMs?: number | null;
  /**
   * Set manually by the timekeeper once the shooter has physically signed the paper card.
   */
  signedOffAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "round-results".
 */
export interface RoundResult {
  id: number;
  membership: number | SquadMembership;
  roundNumber: number;
  status: 'pending' | 'timed' | 'rs' | 'skipped';
  /**
   * Full-precision recorded time in milliseconds, from session/stopped.lastShotTimeMs.
   */
  timeMs?: number | null;
  /**
   * The MQTT session/started.sessionId this round was bound to.
   */
  timerSessionId?: number | null;
  startedAtMs?: number | null;
  stoppedAtMs?: number | null;
  device?: (number | null) | Device;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "match-sessions".
 */
export interface MatchSession {
  id: number;
  device: number | Device;
  status: 'pending' | 'active' | 'completed' | 'abandoned';
  /**
   * Stamped from session/started.sessionId once the range officer presses Start.
   */
  timerSessionId?: number | null;
  startedAtMs?: number | null;
  stoppedAtMs?: number | null;
  /**
   * The round-result this session is bound to — set at activation, the durable (shooter, discipline, round) binding. Exactly one of roundResult / reshootFor is set per session.
   */
  roundResult?: (number | null) | RoundResult;
  /**
   * Set instead of roundResult when this session is a deferred reshoot: the result goes to the membership's reshootTimeMs field, never back into the RS-marked round.
   */
  reshootFor?: (number | null) | SquadMembership;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'shooters';
        value: number | Shooter;
      } | null)
    | ({
        relationTo: 'devices';
        value: number | Device;
      } | null)
    | ({
        relationTo: 'matches';
        value: number | Match;
      } | null)
    | ({
        relationTo: 'squads';
        value: number | Squad;
      } | null)
    | ({
        relationTo: 'squad-memberships';
        value: number | SquadMembership;
      } | null)
    | ({
        relationTo: 'round-results';
        value: number | RoundResult;
      } | null)
    | ({
        relationTo: 'match-sessions';
        value: number | MatchSession;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shooters_select".
 */
export interface ShootersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  asnNumber?: T;
  knsaNumber?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "devices_select".
 */
export interface DevicesSelect<T extends boolean = true> {
  deviceId?: T;
  label?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "matches_select".
 */
export interface MatchesSelect<T extends boolean = true> {
  label?: T;
  device?: T;
  squads?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "squads_select".
 */
export interface SquadsSelect<T extends boolean = true> {
  label?: T;
  match?: T;
  startTime?: T;
  endTime?: T;
  status?: T;
  memberships?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "squad-memberships_select".
 */
export interface SquadMembershipsSelect<T extends boolean = true> {
  squad?: T;
  shooter?: T;
  discipline?: T;
  startingPosition?: T;
  queuePosition?: T;
  status?: T;
  reshootTimeMs?: T;
  signedOffAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "round-results_select".
 */
export interface RoundResultsSelect<T extends boolean = true> {
  membership?: T;
  roundNumber?: T;
  status?: T;
  timeMs?: T;
  timerSessionId?: T;
  startedAtMs?: T;
  stoppedAtMs?: T;
  device?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "match-sessions_select".
 */
export interface MatchSessionsSelect<T extends boolean = true> {
  device?: T;
  status?: T;
  timerSessionId?: T;
  startedAtMs?: T;
  stoppedAtMs?: T;
  roundResult?: T;
  reshootFor?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}